### ISSUE TITLE
Suggestion and bugs

### ISSUE THREAD

**Issue by thezoggy** [apuravchauhan/bootstrap-themeroller#1]
- you should silo the actual customize tab/css so that changing  options dont mess that section up.. changing font size/colors/etc. 
- offer ability to load presets for 2.0.4 / 2.1.1 / etc rather than use placeholder ? maybe offer ability to offer diff of current setting vs preset x
- ability to set image path
- Body and Fonts >  Heading Weight > there are two 'bold' options in dropdown..

**Comment by thezoggy** [comment]
- extend color picker to do rgba on fields that need it? -- http://www.eyecon.ro/bootstrap-colorpicker/

**Comment by apuravchauhan** [comment]
Duplicate bold option issue is fixed and site updated accordingly.

**Comment by thezoggy** [comment]
- should add vertical divider in the navbar... maybe icon in the dropdown as well.. 
- change 'project name' to 'brand' so it matches the customize option 
- should add normal navbar and inverse navbar (2.1.x)
- button group / radio option / other missing elements..

**Comment by kosir** [comment]
bootstrap 3 - any plans to implement it? btw, this app is great! Best bs theme tool around, congrats!

**Comment by macsupport** [comment]
Update to Bootstrap 3!!!!

**Comment by oakley808** [comment]
Great app!  
+1 for updating it to Bootstrap 3

**Comment by SecureCloud-biz** [comment]
So did you just abandon this project?

**you should update to Bootstrap 3**

**IDEA 1:** (or even better, you should create a `lib` folder of different Bootstrap versions & add a dropdown to pick which version you want to work with.) or Pick on 1st screen & load that styles page.

I noticed the `'jsonpi'` is `POSTED` to `http://bootstrap.herokuapp.com` (some Materialize project now)
the "Customize and Download" **DOES NOT WORK ANYMORE** -- So maybe you could fork the code that _USE_ to process the `POSTED` data (`css:js:vars:img`) on the herokuapp site ?

I noticed in the URL bar all the settings you change are there:
`...-roller.html#@linkColor=#1dd919&@headingsFontWeight=bold`
and when you `Share/Save Theme` your can email it & the URL is there.. so with that in mind..

**IDEA 2:**  You should be able to SAVE your project in JSON format (or even the same string saved in a txt file you can name it, then have a dropDown where you can reload a project

as I write this.. (2-17-2015) Bootstrap Versions:
current version is: `v3.3.2`
your last version: `v2.0.4`

You had the right idea, you just stopped working on it & the mistake you made was using a external site to process the data, now its gone.

**IDEA 3:** one of the Bootstrap sample pages has ALL the CSS components on it, 
(http://getbootstrap.com/examples/theme/) .. maybe just use a template page like that... ALSO http://minikomi.github.io/Bootstrap-Form-Builder/  , if you drag a field over.. then click on it you get a PopOver (or modal) where you can change values...
_My Idea Is..._ if you used a page that had ALL the CSS styles on it, and you click on an element & a PopOver or modal pops up where you can change values (colorpicker or whatever) plus there's better color pickers now, like the inline one in Atom.io Editor (personally i like Sublime)

I could make all these changes & basically re-build it, but i dont have the time right now, & my specialty is server-side (PHP & MySQL with Bootstrap front-end).. But all these changes are do-able, and not too hard.. Just takes time, i dont have right now.. But if these changes were in place, this would be the BEST `Bootstrap ThemeRoller` out there.

If you need help let me know.
